'------------------------------------------------------------------------------
' <auto-generated>
'     Dieser Code wurde von einem Tool generiert.
'     Laufzeitversion:4.0.30319.34011
'
'     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
'     der Code erneut generiert wird.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    '-Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    'Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    'mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    '''<summary>
    '''  Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        '''  Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ABOUT_BG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ABOUT_BG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property addsign() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("addsign", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property CONFIG_Button_CLOSE() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CONFIG_Button_CLOSE", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property CONFIG_Button_LINKS_facebook() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CONFIG_Button_LINKS_facebook", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property CONFIG_Button_LINKS_twitter() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CONFIG_Button_LINKS_twitter", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property CONFIG_Button_LINKS_youtube() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CONFIG_Button_LINKS_youtube", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property CONFIGFILES_BG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CONFIGFILES_BG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property CONTEXTMENU_BG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CONTEXTMENU_BG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property CONTROL_OVERLAY() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CONTROL_OVERLAY", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Donate() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Donate", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property LJTD_Button_CLOSE() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LJTD_Button_CLOSE", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property LJTD_Button_MINIMAP() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LJTD_Button_MINIMAP", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property LJTD_Button_MINIMIZE() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LJTD_Button_MINIMIZE", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property LJTD_Button_SLIDE_IN() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LJTD_Button_SLIDE_IN", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property LJTD_Button_SLIDE_OUT() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LJTD_Button_SLIDE_OUT", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property LJTD_Button_START() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LJTD_Button_START", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property LJTD_Button_STOP() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LJTD_Button_STOP", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Icon ähnlich wie (Symbol).
        '''</summary>
        Friend ReadOnly Property LJTD_gray() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("LJTD_gray", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Icon ähnlich wie (Symbol).
        '''</summary>
        Friend ReadOnly Property LJTD_green() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("LJTD_green", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property LJTD_Panel() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LJTD_Panel", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property LJTD_Panel_Vertical() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LJTD_Panel_Vertical", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property LJTD_Settings_Icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LJTD_Settings_Icon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Icon ähnlich wie (Symbol).
        '''</summary>
        Friend ReadOnly Property Loading_animation__frame_0001() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("Loading_animation__frame_0001", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Icon ähnlich wie (Symbol).
        '''</summary>
        Friend ReadOnly Property Loading_animation__frame_0002() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("Loading_animation__frame_0002", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Icon ähnlich wie (Symbol).
        '''</summary>
        Friend ReadOnly Property Loading_animation__frame_0003() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("Loading_animation__frame_0003", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Icon ähnlich wie (Symbol).
        '''</summary>
        Friend ReadOnly Property Loading_animation__frame_0004() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("Loading_animation__frame_0004", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Icon ähnlich wie (Symbol).
        '''</summary>
        Friend ReadOnly Property Loading_animation__frame_0005() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("Loading_animation__frame_0005", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Icon ähnlich wie (Symbol).
        '''</summary>
        Friend ReadOnly Property Loading_animation__frame_0006() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("Loading_animation__frame_0006", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Icon ähnlich wie (Symbol).
        '''</summary>
        Friend ReadOnly Property Loading_animation__frame_0007() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("Loading_animation__frame_0007", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Icon ähnlich wie (Symbol).
        '''</summary>
        Friend ReadOnly Property Loading_animation__frame_0008() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("Loading_animation__frame_0008", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Icon ähnlich wie (Symbol).
        '''</summary>
        Friend ReadOnly Property Loading_animation__frame_0009() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("Loading_animation__frame_0009", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Icon ähnlich wie (Symbol).
        '''</summary>
        Friend ReadOnly Property Loading_animation__frame_0010() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("Loading_animation__frame_0010", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Icon ähnlich wie (Symbol).
        '''</summary>
        Friend ReadOnly Property Loading_animation__frame_0011() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("Loading_animation__frame_0011", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Icon ähnlich wie (Symbol).
        '''</summary>
        Friend ReadOnly Property Loading_animation__frame_0012() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("Loading_animation__frame_0012", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MINIMAP_Button_BLUE_RED() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MINIMAP_Button_BLUE_RED", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MINIMAP_Button_RED_BLUE() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MINIMAP_Button_RED_BLUE", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MINIMAP_Button_Resize() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MINIMAP_Button_Resize", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MINIMAP_Panel() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MINIMAP_Panel", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MINIMAP_Panel_Vertical() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MINIMAP_Panel_Vertical", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MINIMAP_Ward_10sec() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MINIMAP_Ward_10sec", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MINIMAP_Ward_10sec_orig() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MINIMAP_Ward_10sec_orig", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MINIMAP_Ward_180sec() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MINIMAP_Ward_180sec", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MINIMAP_Ward_180sec_orig() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MINIMAP_Ward_180sec_orig", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MINIMAP_Ward_30sec() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MINIMAP_Ward_30sec", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MINIMAP_Ward_30sec_orig() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MINIMAP_Ward_30sec_orig", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MINIMAP_WardMap_SR() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MINIMAP_WardMap_SR", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MINIMAP_WardMap_TT() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MINIMAP_WardMap_TT", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property OBJECTIVE_Baron() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("OBJECTIVE_Baron", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property OBJECTIVE_Baron_Disabled() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("OBJECTIVE_Baron_Disabled", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property OBJECTIVE_Baron_Mousehover() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("OBJECTIVE_Baron_Mousehover", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property OBJECTIVE_Dragon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("OBJECTIVE_Dragon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property OBJECTIVE_Dragon_Disabled() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("OBJECTIVE_Dragon_Disabled", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property OBJECTIVE_Dragon_Mousehover() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("OBJECTIVE_Dragon_Mousehover", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property OBJECTIVE_OB() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("OBJECTIVE_OB", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property OBJECTIVE_OB_Disabled() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("OBJECTIVE_OB_Disabled", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property OBJECTIVE_OB_Mousehover() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("OBJECTIVE_OB_Mousehover", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property OBJECTIVE_OR() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("OBJECTIVE_OR", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property OBJECTIVE_OR_Disabled() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("OBJECTIVE_OR_Disabled", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property OBJECTIVE_OR_Mousehover() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("OBJECTIVE_OR_Mousehover", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property OBJECTIVE_TB() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("OBJECTIVE_TB", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property OBJECTIVE_TB_Disabled() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("OBJECTIVE_TB_Disabled", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property OBJECTIVE_TB_Mousehover() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("OBJECTIVE_TB_Mousehover", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property OBJECTIVE_TR() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("OBJECTIVE_TR", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property OBJECTIVE_TR_Disabled() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("OBJECTIVE_TR_Disabled", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property OBJECTIVE_TR_Mousehover() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("OBJECTIVE_TR_Mousehover", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property OBJECTIVE_Vilemaw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("OBJECTIVE_Vilemaw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property OBJECTIVE_Vilemaw_Disabled() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("OBJECTIVE_Vilemaw_Disabled", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property OBJECTIVE_Vilemaw_Mousehover() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("OBJECTIVE_Vilemaw_Mousehover", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property SETTINGS_BG_CHAT() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SETTINGS_BG_CHAT", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property SETTINGS_BG_COLOR() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SETTINGS_BG_COLOR", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property SETTINGS_BG_Hotkey() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SETTINGS_BG_Hotkey", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property SETTINGS_BG_MACROS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SETTINGS_BG_MACROS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property SETTINGS_BG_MAIN() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SETTINGS_BG_MAIN", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property SETTINGS_BG_MINIMAP() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SETTINGS_BG_MINIMAP", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property SETTINGS_BG_VISUAL() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SETTINGS_BG_VISUAL", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property SETTINGS_Button_BASIC() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SETTINGS_Button_BASIC", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property SETTINGS_Button_RESET() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SETTINGS_Button_RESET", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property SETTINGS_Button_SAVE() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SETTINGS_Button_SAVE", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property SETTINGS_ButtonEXPERT() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SETTINGS_ButtonEXPERT", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property SETTINGS_Tab_Chat() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SETTINGS_Tab_Chat", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property SETTINGS_Tab_Color() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SETTINGS_Tab_Color", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property SETTINGS_Tab_Hotkey() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SETTINGS_Tab_Hotkey", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property SETTINGS_Tab_Macros() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SETTINGS_Tab_Macros", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property SETTINGS_Tab_Main() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SETTINGS_Tab_Main", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property SETTINGS_Tab_Minimap() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SETTINGS_Tab_Minimap", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property SETTINGS_Tab_Visual() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SETTINGS_Tab_Visual", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TEAMSYNC_BG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TEAMSYNC_BG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property UPDATER_BG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("UPDATER_BG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property WIZARD_BG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("WIZARD_BG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
